<a href="https://colab.research.google.com/github/brainer3220/Jeju_CreditCard_Compete/blob/master/%EC%A0%9C%EC%A3%BC_%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0_%EA%B2%BD%EC%A7%84%EB%8C%80%ED%9A%8C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from datetime import datetime

import plotly.graph_objs as go
import plotly.offline as py
import plotly.express as px

from fbprophet import Prophet
from fbprophet.plot import plot_plotly, add_changepoints_to_plot

import seaborn as sns
import matplotlib.pyplot as plt

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning:

pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.



In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Google Drive Sync

In [3]:
Data = 'drive/My Drive/Brainer 공유 Drive/Colab/제주 빅데이터 경진대회/Data/'

In [4]:
Submission = pd.read_csv(Data + "submission.csv")
Submission.head(3)

id  REG_YYMM CARD_SIDO_NM  STD_CLSS_NM  AMT
0   0    202004           강원   건강보조식품 소매업    0
1   1    202004           강원      골프장 운영업    0
2   2    202004           강원  과실 및 채소 소매업    0

In [5]:
df = pd.read_csv(Data + "201901-202003.csv")
df.head(3)

REG_YYMM CARD_SIDO_NM CARD_CCG_NM STD_CLSS_NM  ... FLC CSTMR_CNT      AMT  CNT
0    201901           강원         강릉시  건강보조식품 소매업  ...   1         4   311200    4
1    201901           강원         강릉시  건강보조식품 소매업  ...   2         7  1374500    8
2    201901           강원         강릉시  건강보조식품 소매업  ...   2         6   818700    6

[3 rows x 12 columns]

# Data Preprocessing

## SEX One Hot Encoding


In [6]:
enc = OneHotEncoder()

SEX_List = np.array(df.SEX_CTGO_CD.tolist()).reshape(-1, 1)

enc.fit(SEX_List)
SEX_OneHot = enc.transform(SEX_List).toarray()
SEX_OneHot_Series = pd.DataFrame(SEX_OneHot).rename(columns = {0: 'Male', 1: 'FeMale'})

df = pd.concat([df, SEX_OneHot_Series], axis=1)

del SEX_OneHot, SEX_OneHot_Series, SEX_List, df['SEX_CTGO_CD']

## REG_YYMM(Integer) to TimeStamp

In [7]:
REG_Date = pd.to_datetime(df['REG_YYMM'], format='%Y%m', errors='ignore')

del df['REG_YYMM']

df = pd.concat([REG_Date, df], axis=1)

del REG_Date

# Data Check

In [8]:
df.head(3)

REG_YYMM CARD_SIDO_NM CARD_CCG_NM STD_CLSS_NM  ...      AMT CNT Male  FeMale
0 2019-01-01           강원         강릉시  건강보조식품 소매업  ...   311200   4  1.0     0.0
1 2019-01-01           강원         강릉시  건강보조식품 소매업  ...  1374500   8  1.0     0.0
2 2019-01-01           강원         강릉시  건강보조식품 소매업  ...   818700   6  0.0     1.0

[3 rows x 13 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24697792 entries, 0 to 24697791
Data columns (total 13 columns):
 #   Column        Dtype         
---  ------        -----         
 0   REG_YYMM      datetime64[ns]
 1   CARD_SIDO_NM  object        
 2   CARD_CCG_NM   object        
 3   STD_CLSS_NM   object        
 4   HOM_SIDO_NM   object        
 5   HOM_CCG_NM    object        
 6   AGE           object        
 7   FLC           int64         
 8   CSTMR_CNT     int64         
 9   AMT           int64         
 10  CNT           int64         
 11  Male          float64       
 12  FeMale        float64       
dtypes: datetime64[ns](1), float64(2), int64(4), object(6)
memory usage: 2.4+ GB


In [10]:
df.describe()

FLC     CSTMR_CNT  ...          Male        FeMale
count  2.469779e+07  2.469779e+07  ...  2.469779e+07  2.469779e+07
mean   2.804429e+00  6.196855e+01  ...  5.873553e-01  4.126447e-01
std    1.375455e+00  3.559175e+02  ...  4.923099e-01  4.923099e-01
min    1.000000e+00  3.000000e+00  ...  0.000000e+00  0.000000e+00
25%    2.000000e+00  4.000000e+00  ...  0.000000e+00  0.000000e+00
50%    3.000000e+00  8.000000e+00  ...  1.000000e+00  0.000000e+00
75%    4.000000e+00  2.400000e+01  ...  1.000000e+00  1.000000e+00
max    5.000000e+00  3.281300e+04  ...  1.000000e+00  1.000000e+00

[8 rows x 6 columns]

## Null Check

In [11]:
df.isnull().sum()

REG_YYMM             0
CARD_SIDO_NM         0
CARD_CCG_NM      87213
STD_CLSS_NM          0
HOM_SIDO_NM          0
HOM_CCG_NM      147787
AGE                  0
FLC                  0
CSTMR_CNT            0
AMT                  0
CNT                  0
Male                 0
FeMale               0
dtype: int64

In [12]:
for col in df.columns:
    msg = 'column: {:>10}\t Percent of NaN value: {:.2f}%'.format(col, 100 * (df[col].isnull().sum() / df[col].shape[0]))
    print(msg)

column:   REG_YYMM	 Percent of NaN value: 0.00%
column: CARD_SIDO_NM	 Percent of NaN value: 0.00%
column: CARD_CCG_NM	 Percent of NaN value: 0.35%
column: STD_CLSS_NM	 Percent of NaN value: 0.00%
column: HOM_SIDO_NM	 Percent of NaN value: 0.00%
column: HOM_CCG_NM	 Percent of NaN value: 0.60%
column:        AGE	 Percent of NaN value: 0.00%
column:        FLC	 Percent of NaN value: 0.00%
column:  CSTMR_CNT	 Percent of NaN value: 0.00%
column:        AMT	 Percent of NaN value: 0.00%
column:        CNT	 Percent of NaN value: 0.00%
column:       Male	 Percent of NaN value: 0.00%
column:     FeMale	 Percent of NaN value: 0.00%


# Graph Figure

In [13]:
AmountDate = df.groupby('REG_YYMM').sum()

del AmountDate['FLC'], AmountDate['CSTMR_CNT'], AmountDate['CNT'], AmountDate['Male'], AmountDate['FeMale']


REG_YYMM =  df['REG_YYMM'].drop_duplicates()

if len(REG_YYMM) == len(AmountDate):
    AmountDate = pd.concat([pd.DataFrame(REG_YYMM.to_list(), columns =['REG_YYMM']) , pd.DataFrame(AmountDate['AMT'].to_list(), columns =['AMT'])], axis=1)

AmountDate.head(3)

REG_YYMM            AMT
0 2019-01-01  4052317259025
1 2019-02-01  3634345832156
2 2019-03-01  4105409759731

## Monthly

In [14]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=AmountDate.REG_YYMM,
        y=AmountDate.AMT,
        name='날짜별 AMT'
    )
)

fig

## 달별, 도시별 카드 사용량

In [15]:
SidoByDate = df.groupby(['REG_YYMM', 'CARD_SIDO_NM']).sum()
del SidoByDate['FLC'], SidoByDate['CSTMR_CNT'], SidoByDate['CNT'], SidoByDate['Male'], SidoByDate['FeMale']
pd.DataFrame(SidoByDate)

SidoByDate.reset_index(level=0, inplace=True)
SidoByDate.reset_index(level=0, inplace=True)

SidoByDate

CARD_SIDO_NM   REG_YYMM           AMT
0             강원 2019-01-01  106565971761
1             경기 2019-01-01  926766490511
2             경남 2019-01-01  233964871967
3             경북 2019-01-01  178450257323
4             광주 2019-01-01  114443191321
..           ...        ...           ...
250           전남 2020-03-01  116584279973
251           전북 2020-03-01  118942183199
252           제주 2020-03-01   71061095855
253           충남 2020-03-01  124325365579
254           충북 2020-03-01   89186871346

[255 rows x 3 columns]

In [16]:
fig = px.line_3d(SidoByDate, x="REG_YYMM", y="CARD_SIDO_NM", z="AMT")
fig.show()

## 달별, 업종별 카드 사용량

In [17]:
ClassByDate = df.groupby(['REG_YYMM', 'STD_CLSS_NM']).sum()
del ClassByDate['FLC'], ClassByDate['CSTMR_CNT'], ClassByDate['CNT'], ClassByDate['Male'], ClassByDate['FeMale']
pd.DataFrame(ClassByDate)

ClassByDate.reset_index(level=0, inplace=True)
ClassByDate.reset_index(level=0, inplace=True)

ClassByDate

STD_CLSS_NM   REG_YYMM           AMT
0               건강보조식품 소매업 2019-01-01    8605074944
1                  골프장 운영업 2019-01-01   11968748603
2              과실 및 채소 소매업 2019-01-01   44453112689
3        관광 민예품 및 선물용품 소매업 2019-01-01     955750428
4     그외 기타 분류안된 오락관련 서비스업 2019-01-01       1017500
..                     ...        ...           ...
610  피자 햄버거 샌드위치 및 유사 음식점업 2020-03-01   65972238656
611                한식 음식점업 2020-03-01  666573459086
612                    호텔업 2020-03-01    5073633041
613          화장품 및 방향제 소매업 2020-03-01   31002789304
614               휴양콘도 운영업 2020-03-01    1093634463

[615 rows x 3 columns]

In [18]:
fig = px.line_3d(ClassByDate, x="REG_YYMM", y="STD_CLSS_NM", z="AMT")
fig.show()

## 달별, 지역별, 업종별 카드 사용량

In [19]:
SidoToClassByDate = df.groupby(['REG_YYMM', 'CARD_SIDO_NM','STD_CLSS_NM']).sum()
del SidoToClassByDate['FLC'], SidoToClassByDate['CSTMR_CNT'], SidoToClassByDate['CNT'], SidoToClassByDate['Male'], SidoToClassByDate['FeMale']
pd.DataFrame(SidoToClassByDate)

SidoToClassByDate.reset_index(level=0, inplace=True)
SidoToClassByDate.reset_index(level=0, inplace=True)
SidoToClassByDate.reset_index(level=0, inplace=True)

SidoToClassByDate

STD_CLSS_NM CARD_SIDO_NM   REG_YYMM          AMT
0                건강보조식품 소매업           강원 2019-01-01    148354746
1                   골프장 운영업           강원 2019-01-01   1229200312
2               과실 및 채소 소매업           강원 2019-01-01   1286979106
3         관광 민예품 및 선물용품 소매업           강원 2019-01-01     30656770
4           그외 기타 스포츠시설 운영업           강원 2019-01-01     13101500
...                     ...          ...        ...          ...
9433  피자 햄버거 샌드위치 및 유사 음식점업           충북 2020-03-01   1315245299
9434                한식 음식점업           충북 2020-03-01  16152482704
9435                    호텔업           충북 2020-03-01     15248550
9436          화장품 및 방향제 소매업           충북 2020-03-01    428881434
9437               휴양콘도 운영업           충북 2020-03-01     12733490

[9438 rows x 4 columns]

## 성별별, 날짜별

In [20]:
SexByDate = df.groupby(['REG_YYMM', 'Male']).sum()
del SexByDate['FLC'], SexByDate['CSTMR_CNT'], SexByDate['CNT'], SexByDate['FeMale']
pd.DataFrame(SexByDate)

SexByDate.reset_index(level=0, inplace=True)
SexByDate.reset_index(level=0, inplace=True)
SexByDate.reset_index(level=0, inplace=True)

SexByDate.head(3)

index  Male   REG_YYMM            AMT
0      0   0.0 2019-01-01  1627661194843
1      1   1.0 2019-01-01  2424656064182
2      2   0.0 2019-02-01  1452925892309

In [21]:
fig = px.scatter_3d(SexByDate, x='Male', y='REG_YYMM', z='AMT',
              color='Male')
fig.show()

## 업종별 성별

In [22]:
ClassBySex = df.groupby(['STD_CLSS_NM', 'Male']).sum()
del ClassBySex['FLC'], ClassBySex['CSTMR_CNT'], ClassBySex['CNT'], ClassBySex['FeMale']
pd.DataFrame(SexByDate)

ClassBySex.reset_index(level=0, inplace=True)
ClassBySex.reset_index(level=0, inplace=True)
ClassBySex.reset_index(level=0, inplace=True)

ClassBySex.head(3)

index  Male STD_CLSS_NM          AMT
0      0   0.0  건강보조식품 소매업  60543938037
1      1   1.0  건강보조식품 소매업  44582426343
2      2   0.0     골프장 운영업  99447245024

In [23]:
fig = px.scatter_3d(ClassBySex, x='Male', y='STD_CLSS_NM', z='AMT',
              color='Male')
fig.show()

# Learning and Training

In [24]:
y_train = SidoToClassByDate.T[3:].T
y_train

AMT
0       148354746
1      1229200312
2      1286979106
3        30656770
4        13101500
...           ...
9433   1315245299
9434  16152482704
9435     15248550
9436    428881434
9437     12733490

[9438 rows x 1 columns]

In [25]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
encoder.fit(SidoToClassByDate.T[2:-1].T)

X_trainDateEncoded = encoder.transform(SidoToClassByDate.T[2:-1].T)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



In [26]:
SidoToClassByDate.T[:-2].T

STD_CLSS_NM CARD_SIDO_NM
0                건강보조식품 소매업           강원
1                   골프장 운영업           강원
2               과실 및 채소 소매업           강원
3         관광 민예품 및 선물용품 소매업           강원
4           그외 기타 스포츠시설 운영업           강원
...                     ...          ...
9433  피자 햄버거 샌드위치 및 유사 음식점업           충북
9434                한식 음식점업           충북
9435                    호텔업           충북
9436          화장품 및 방향제 소매업           충북
9437               휴양콘도 운영업           충북

[9438 rows x 2 columns]

In [27]:
# list(Submission['REG_YYMM'].replace(202004, 15).replace(202007, 18))

In [28]:
# del Submission['REG_YYMM']

Submit = pd.concat([Submission['STD_CLSS_NM'], Submission['CARD_SIDO_NM']], axis=1)
Submit = pd.get_dummies(Submit)
# del SubPlusTrain['AMT']
Submit

# Submission['STD_CLSS_NM'], Submission['CARD_SIDO_NM']
# SidoToClassByDate

STD_CLSS_NM_건강보조식품 소매업  ...  CARD_SIDO_NM_충북
0                          1  ...                0
1                          0  ...                0
2                          0  ...                0
3                          0  ...                0
4                          0  ...                0
...                      ...  ...              ...
1389                       0  ...                1
1390                       0  ...                1
1391                       0  ...                1
1392                       0  ...                1
1393                       0  ...                1

[1394 rows x 58 columns]

In [29]:
x_train = pd.get_dummies(SidoToClassByDate.T[:-2].T)

x_train = pd.concat([pd.DataFrame(X_trainDateEncoded), x_train], axis=1)
x_train

0  STD_CLSS_NM_건강보조식품 소매업  ...  CARD_SIDO_NM_충남  CARD_SIDO_NM_충북
0      0                       1  ...                0                0
1      0                       0  ...                0                0
2      0                       0  ...                0                0
3      0                       0  ...                0                0
4      0                       0  ...                0                0
...   ..                     ...  ...              ...              ...
9433  14                       0  ...                0                1
9434  14                       0  ...                0                1
9435  14                       0  ...                0                1
9436  14                       0  ...                0                1
9437  14                       0  ...                0                1

[9438 rows x 59 columns]

In [30]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso

mlr = LinearRegression()
mlr.fit(x_train, y_train)

mlr.predict(x_train)

array([[-2.54364877e+09],
       [-6.19839488e+08],
       [-5.28351232e+08],
       ...,
       [-3.35806464e+09],
       [-1.32841472e+09],
       [-3.42995763e+09]])

In [31]:
ridge_reg = Ridge()
ridge_reg.fit(x_train, y_train)

ridge_reg.predict(x_train)

array([[-2.51998186e+09],
       [-6.03670908e+08],
       [-5.12941094e+08],
       ...,
       [-3.32728786e+09],
       [-1.30918476e+09],
       [-3.38604351e+09]])

In [32]:
lasso_reg = Lasso()
lasso_reg.fit(x_train, y_train)

lasso_reg.predict(x_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations. Duality gap: 2.9184752210119868e+23, tolerance: 3.398124001385555e+20



array([-2.54465704e+09, -6.20831143e+08, -5.29745524e+08, ...,
       -3.35771930e+09, -1.32882407e+09, -3.43037033e+09])

In [33]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor

k_fold = KFold(n_splits=10, shuffle=True, random_state=0)

max_depth_list = []

model = RandomForestRegressor(n_estimators=100,
                              n_jobs=-1,
                              random_state=0)
model


model.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:15: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().



RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=-1, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [34]:
y_train[0:10]

AMT
0   148354746
1  1229200312
2  1286979106
3    30656770
4    13101500
5   533330540
6  8442324759
7     4224000
8  1164632486
9   326489689

In [35]:
Submit = pd.concat([pd.DataFrame(Submission['REG_YYMM'].replace(202004, 15).replace(202007, 18)), Submit], axis=1)
Submit

REG_YYMM  STD_CLSS_NM_건강보조식품 소매업  ...  CARD_SIDO_NM_충남  CARD_SIDO_NM_충북
0           15                       1  ...                0                0
1           15                       0  ...                0                0
2           15                       0  ...                0                0
3           15                       0  ...                0                0
4           15                       0  ...                0                0
...        ...                     ...  ...              ...              ...
1389        18                       0  ...                0                1
1390        18                       0  ...                0                1
1391        18                       0  ...                0                1
1392        18                       0  ...                0                1
1393        18                       0  ...                0                1

[1394 rows x 59 columns]

In [36]:
# 예측
predictions = model.predict(Submit)

print(predictions.shape)
predictions[0:10]

(1394,)


array([9.41784526e+07, 2.35038113e+09, 9.88906754e+08, 1.66280007e+07,
       9.60005200e+05, 2.78505700e+06, 4.73531727e+08, 6.59972454e+09,
       9.51445000e+05, 8.58655018e+08])

In [37]:
Submission['AMT'] = predictions
Submission.head(3)

id  REG_YYMM CARD_SIDO_NM  STD_CLSS_NM           AMT
0   0    202004           강원   건강보조식품 소매업  9.417845e+07
1   1    202004           강원      골프장 운영업  2.350381e+09
2   2    202004           강원  과실 및 채소 소매업  9.889068e+08

In [38]:
Submission = Submission.set_index('id')
Submission.to_csv('drive/My Drive/Brainer 공유 Drive/Colab/제주 빅데이터 경진대회/Submission.csv', encoding='utf-8-sig')

In [39]:
Submission.head(3)

REG_YYMM CARD_SIDO_NM  STD_CLSS_NM           AMT
id                                                  
0     202004           강원   건강보조식품 소매업  9.417845e+07
1     202004           강원      골프장 운영업  2.350381e+09
2     202004           강원  과실 및 채소 소매업  9.889068e+08

In [40]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        # x=pd.to_datetime(Submission['REG_YYMM'], format='%Y%m', errors='ignore'),
        y=Submission.AMT,
        name='최종 제출'
    )
)

fig

fig = px.scatter_3d(Submission, x=pd.to_datetime(Submission['REG_YYMM'], format='%Y%m', errors='ignore'), y='CARD_SIDO_NM', z='AMT',
              color='STD_CLSS_NM')
fig.show()